version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3307"
    networks:
      - app-network
    restart: always

  app:
    build: .
    container_name: springboot-app
    environment:
      DB_URL: jdbc:mysql://mysql-db:3306/app_db
      DB_USERNAME: app_user
      DB_PASSWORD: app_pass
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge
